// v0.8.2.1 "Room to Breathe": the legal reader and its single source, the legal wording, the mobile shell, button contrast, pile browsing, video links.
//   node v0821.test.mjs
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
import { parseHTML } from 'linkedom';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..', '..');
const read = (f) => fs.readFileSync(path.join(root, f), 'utf8').replace(/\r\n/g, '\n');
const app = read('js/app.js'), css = read('css/app.css'), rcss = read('css/legal-reader.css');
let pass = 0, fail = 0;
const ok = (c, m) => { if (c) pass++; else { fail++; console.log('  FAIL  ' + m); } };
const fn = (name) => { const i = app.indexOf('function ' + name + '('); if (i < 0) return ''; let d = 0, j = app.indexOf('{', i); for (; j < app.length; j++) { if (app[j] === '{') d++; else if (app[j] === '}') { d--; if (!d) break; } } return app.slice(i, j + 1); };

// ================================================================ LEGAL: one source, two outputs
const loadScript = (ctx, f) => vm.runInContext(read(f), ctx, { filename: f });
const base = vm.createContext({ console, Math, Date, Object, Array, JSON, RegExp, String, Number });
vm.runInContext('var window = globalThis; Stick = {};', base);
['js/lang.js', 'js/legal-config.js', 'js/legal-content.js'].forEach((f) => loadScript(base, f));
const C = base.Stick.legalContent;
ok(C.order.length === 6 && ['privacy', 'terms', 'copyright', 'young', 'storage', 'accessibility'].every((k) => C.order.includes(k)), 'the reader knows all six documents');
const article = (html) => { const m = /<article>\n([\s\S]*?)\n<\/article>/.exec(html); return m ? m[1] : null; };
for (const lang of ['en', 'he']) for (const id of C.order) {
  const d = C.docs[lang][id], file = (lang === 'he' ? 'legal/he/' : 'legal/') + d.file;
  ok(article(read(file)) === d.html, 'standalone ' + file + ' and the in-app reader carry the identical generated text (one source, no drift)');
}
ok(/legal-fill\.js/.test(read('legal/privacy.html')) && /legal-fill\.js/.test(read('legal/he/privacy.html')), 'standalone pages use the shared fill rules');
ok(!/openPlaceholder|Privacy Policy \(DRAFT\)/.test(read('js/legal-reader.js')), 'the reader holds no legal prose of its own');
ok(/Stick\.legalContent/.test(read('js/legal-reader.js')) && /legalFill/.test(read('js/legal-reader.js')), 'the reader renders legal-content.js with the shared fill rules');
const gen = read('js/legal-content.js'); ok(/GENERATED by tools\/build-legal\.py/.test(gen), 'legal-content.js is generated, not hand-written');
ok(['privacy.html', 'terms.html', 'storage.html', 'accessibility.html', 'copyright.html', 'young-people.html'].every((f) => fs.existsSync(path.join(root, 'legal', f)) && fs.existsSync(path.join(root, 'legal', 'he', f))), 'every standalone legal URL still exists (English and Hebrew)');
const langList = base.Stick.lang.complete('legal').map((l) => l.code).join();
ok(langList === 'en,he', 'only complete legal languages are offered (English, Hebrew)');
ok(/<svg/.test(base.Stick.lang.iconSvg(20)) && /א/.test(base.Stick.lang.iconSvg(20)) && /中/.test(base.Stick.lang.iconSvg(20)) && /ع/.test(base.Stick.lang.iconSvg(20)) && />A</.test(base.Stick.lang.iconSvg(20)) && /currentColor/.test(base.Stick.lang.iconSvg(20)), 'the language icon is a currentColor SVG with A, א, 中, ع');

// ---- the reader, on a real DOM
{
  const { window, document } = parseHTML('<html><head></head><body><button id="opener">open</button></body></html>');
  window.matchMedia = () => ({ matches: false });
  const store = {}; window.localStorage = { getItem: (k) => (k in store ? store[k] : null), setItem: (k, v) => { store[k] = String(v); } };
  const ctx = vm.createContext(window); ctx.window = window; ctx.Stick = {}; ctx.document = document; ctx.localStorage = window.localStorage; ctx.console = console;
  ['js/lang.js', 'js/legal-config.js', 'js/legal-fill.js', 'js/legal-content.js', 'js/legal-reader.js'].forEach((f) => vm.runInContext(read(f), ctx, { filename: f }));
  const R = ctx.Stick.legalReader;
  const layers = []; let closeFn = null;
  R.init({ layer: (id, close, isOpen) => { closeFn = close; layers.push(id); return { open() {}, close() {} }; }, logo: () => '<svg id="lg"></svg>' });
  const opener = document.getElementById('opener'); opener.focus && opener.focus();
  R.open('privacy');
  ok(R.isOpen() && document.querySelector('.lrSheet') && document.querySelector('.lrSheet').getAttribute('role') === 'dialog' && document.querySelector('.lrSheet').getAttribute('aria-modal') === 'true', 'the reader opens as a modal dialog');
  ok(document.querySelectorAll('.lrDoc').length === 6, 'all six documents are in the navigation');
  ok(document.querySelector('.lrArticle h1').textContent.indexOf('Privacy') !== -1, 'Privacy opens first');
  ok(document.querySelector('.lrMark #lg'), 'the brand logo is drawn from the app logo (vector)');
  ok(document.querySelector('.lrBrand').getAttribute('aria-label') === 'Stick-It', 'the logo has an accessible name');
  [...document.querySelectorAll('.lrDoc')].find((b) => b.textContent === 'Storage').click();
  ok(document.querySelector('.lrArticle h1').textContent.indexOf('Storage') !== -1 && document.querySelector('.lrDoc[aria-current="page"]').textContent === 'Storage', 'switching document shows it and marks it current');
  ok(document.querySelector('.lrTop') && /Back to top/.test(document.querySelector('.lrTop').textContent), 'each document ends with Back to top');
  // Hebrew
  document.querySelector('.lrTools .lrBtn').click();
  const items = [...document.querySelectorAll('.lrItem')]; ok(items.length === 2 && items.map((i) => i.textContent).join('|').includes('English') && items.map((i) => i.textContent).join('|').includes('עברית'), 'the language menu lists only English and Hebrew');
  items.find((i) => i.lang === 'he').click();
  ok(document.querySelector('.lrSheet').getAttribute('dir') === 'rtl' && document.querySelector('.lrArticle').getAttribute('dir') === 'rtl' && document.querySelector('.lrArticle').lang === 'he', 'Hebrew is right-to-left');
  ok(store['stickit.legal.lang'] === 'he', 'the language choice is remembered');
  ok(/הודעת אחסון/.test(document.querySelector('.lrArticle h1').textContent), 'the Hebrew Storage notice is shown');
  // reading options
  document.querySelector('.lrOpts input[value="large"]').dispatchEvent(new window.Event('change'));
  ok(document.querySelector('.lrSheet').getAttribute('data-size') === 'large', 'text size can be made large');
  ok(JSON.parse(store['stickit.legal.read']).size === 'large', 'reading options are remembered');
  document.querySelector('.lrOpts input[name="lr-contrast"][value="on"]').dispatchEvent(new window.Event('change'));
  ok(document.querySelector('.lrSheet').classList.contains('lrContrast'), 'high contrast can be switched on');
  // Esc: a popover first, then the reader
  ok(layers.indexOf('legal-reader') !== -1, 'the reader is a registered layer, so Esc closes the topmost one');
  closeFn(); ok(!R.isOpen(), 'Esc closes the reader');
  ok(document.querySelectorAll('.lrBackdrop').length === 0, 'closing removes the reader from the page');
  // deep link from the sign-in text style: relative links inside a document switch document
  R.open('privacy', { lang: 'en' });
  const young = [...document.querySelectorAll('.lrArticle a')].find((a) => a.getAttribute('href') === 'young-people.html');
  ok(young, 'the Privacy Policy links to the Young people page'); if (young) { young.dispatchEvent(new window.Event('click', { cancelable: true })); ok(document.querySelector('.lrDoc[aria-current="page"]').textContent.indexOf('Young') === 0, 'a link to another legal document opens it in the reader'); }
  R.close();
  // DRAFT markers are still visible
  R.open('copyright'); ok(document.querySelector('.lrBanner') && /Development-only|DMCA/.test(document.querySelector('.lrBanner').textContent), 'the DRAFT / development-only banner is shown in the reader'); R.close();
}

// ================================================================ LEGAL: what the text says (and no longer says)
const en = (id) => C.docs.en[id].html.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ');
const he = (id) => C.docs.he[id].html.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ');
const priv = en('privacy'), stor = en('storage'), acc = en('accessibility'), cpy = en('copyright'), young = en('young');
ok(!/without reading your content/i.test(priv) && !/does not have access to/i.test(priv), 'Privacy no longer claims it cannot access content');
ok(/does not routinely inspect your private content/i.test(priv) && /reported or reasonably suspected/i.test(priv), 'Privacy: no routine inspection, with the limited reasons for access');
ok(/not currently collect your phone number/i.test(priv) && /updated before those features collect that information/i.test(priv), 'Privacy: phone, payment, contacts and location are not current collection, and any future use is announced first');
ok(/not by itself agreement to marketing|merely/i.test(priv) || /would not by itself be agreement to marketing/i.test(priv), 'Privacy: giving a phone number is not marketing consent');
ok(/No payment provider is active today/i.test(priv) && !/stripe/i.test(priv), 'Privacy: no payment provider is claimed active, none is named');
ok(/currently does not set its own browser cookies/i.test(priv) && /local storage and IndexedDB/i.test(priv) && /technically different from cookies/i.test(priv), 'Privacy: cookie wording is the browser-storage explanation');
ok(!/no analytics/i.test(priv) && /product analytics may be introduced/i.test(priv), 'Privacy: no absolute no-analytics promise');
ok(/reasonably determine that an account used false age information/i.test(priv) && !/forever|immediately/i.test(priv.split('False age information')[1].slice(0, 700)), 'Privacy: measured wording about false age information');
ok(!/not responsible for any illegal/i.test(priv) && /responsible for making sure/i.test(priv), 'Privacy: responsibility wording is measured, not absolute');
ok(/video provider/i.test(priv) && !/youtube|vimeo/i.test(priv + stor + acc + cpy + young), 'embedded video is mentioned conditionally and no provider is named in legal text');
ok(!/no advertising, analytics or session-recording/i.test(stor) && /does not currently use advertising or session-recording/i.test(stor) && /Product analytics may be introduced/i.test(stor), 'Storage: analytics wording is accurate and conditional');
ok(/note text, comment text, search queries/i.test(stor), 'Storage: analytics would never collect content');
ok(/about an hour/i.test(stor) && /90 days/i.test(stor) && /session storage/i.test(stor), 'Storage: the age-step copies and the invitation key match the code');
ok(/WCAG 2\.2 Level AA/.test(acc) && /SI 5568/.test(acc) && /not simply the same thing as WCAG/i.test(acc) && !/certified|certificate of conformance is/i.test(acc.replace(/not a certificate/gi, '')), 'Accessibility: WCAG target and SI 5568 are separate, no certification claimed');
ok(/screen reader|NVDA/i.test(acc) && /physical phones/i.test(acc) && /Known limitations/i.test(acc), 'Accessibility: known limitations are kept and extended');
ok(/accessibility \/ support e-mail|support\.stickit@gmail\.com/i.test(acc) && /assistive technology/i.test(acc), 'Accessibility: contact kept; users are invited to say what they tried and which technology');
ok(/Users are responsible for making sure they have the rights/i.test(cpy) && /does not proactively inspect every private board/i.test(cpy) && /not a registered DMCA designated agent/i.test(cpy) && !/no responsibility/i.test(cpy), 'Copyright: measured responsibility, general contact is not a registered agent');
ok(/\[OWNER INPUT REQUIRED/.test(C.docs.en.copyright.html) || /todo/.test(C.docs.en.copyright.html), 'Copyright: the open owner/legal items are still marked');
ok(['privacy', 'storage', 'accessibility', 'copyright', 'young', 'terms'].every((id) => /DRAFT|Draft|draft|Development-only/.test(C.docs.en[id].html)), 'every document is still marked DRAFT');
ok(/class="todo"/.test(C.docs.en.privacy.html) && /class="todo"/.test(C.docs.en.accessibility.html), 'OWNER INPUT / LEGAL REVIEW markers are still there');
ok(!/no advertising, analytics or tracking/i.test(young), 'Young people: the absolute analytics line is corrected (minimal consistency fix)');
ok(/false age information/i.test(he('privacy')) === false && /מידע גיל כוזב/.test(he('privacy')), 'the Hebrew Privacy Policy carries the false-age wording');
ok(/אינה מציבה עוגיות משלה/.test(he('storage')), 'the Hebrew Storage notice carries the cookie wording');
const cfg = base.Stick.legal; ok(cfg.draft === true && cfg.dmcaRegistered === false, 'legal status stays DRAFT and no DMCA agent is claimed');
ok(!/ו?\bP\.?O\.? ?Box\b|Rothschild|\d{1,3} [A-Z][a-z]+ (St|Street|Ave)/.test(read('js/legal-config.js') + C.docs.en.privacy.html), 'no postal address appears in the legal text or config');
ok(/(^|\n)\.bw\{ font-weight:600; font-style:normal; text-decoration:none; \}/.test(read('legal/legal.css')) && /\.lrArticle \.bw\{ font-weight:600; font-style:normal; text-decoration:none; \}/.test(rcss), 'the Stick-It brand word is semibold and never underlined');
ok((C.docs.en.privacy.html.match(/class="bw"/g) || []).length > 10, 'the brand word treatment is applied in running text');

// ================================================================ LEGAL entry points and footer
ok(!/LEGAL_LINKS\.forEach/.test(app), 'the seven-link legal row is gone from the canvas');
ok(/className = "legalChip"/.test(fn('legalLinksEl')) && (fn('legalLinksEl').match(/createElement\("a"\)/g) || []).length === 1, 'the footer is a single compact Legal chip');
ok(/Stick\.legalReader\.open\("privacy"\)/.test(fn('legalLinksEl')) && /href = "legal\/privacy\.html"/.test(fn('legalLinksEl')), 'the chip opens the in-app reader and keeps a real standalone link');
ok(/Stick\.legalReader\.open\(docId\)/.test(app) && /Stick\.legalReader\.open\("privacy", \{lang: l\.code\}\)/.test(app), 'Settings > Legal & About opens each document (and each language) in the reader');
ok(/Stick\.legalReader\.init\(\{layer: OV\.layer/.test(app), 'the reader joins the one Esc / layer system');
ok(/legal-reader\.js/.test(read('index.html')) && /legal-content\.js/.test(read('index.html')) && /legal-reader\.css/.test(read('index.html')), 'the app page loads the reader');
ok(/\.legalFoot\{[^}]*position:fixed;/.test(rcss) && /\.legalChip/.test(rcss), 'the Legal chip is small and fixed, not a full-width bar');
ok(/@media \(max-width:640px\)/.test(rcss) && /\.lrBtn\{ min-height:44px; min-width:44px/.test(rcss), 'the reader is full-screen on phones with 44px controls');
ok(/prefers-reduced-motion/.test(rcss) && /lrCalm/.test(rcss) && /behavior: smooth|smooth/.test(read('js/legal-reader.js')) && /reduceSystem\(\)/.test(read('js/legal-reader.js')), 'reduced motion is respected (smooth scroll only when motion is allowed)');
ok(/body\.dark \.lrSheet/.test(rcss), 'the reader has a dark mode');
ok(/cursor:url|pencil/i.test(rcss + css) === false, 'no custom pencil cursor exists in this build to reuse (documented)');

// ================================================================ MOBILE shell, search, view-only strip, Done pile
ok(/@media \(max-width:600px\)\{[\s\S]*\.searchWrap\{ display:none; \}[\s\S]*\.searchToggle\{ display:flex; \}/.test(css), 'phones: Search collapses to an icon');
ok(/body\.searchOpen \.searchWrap\{ display:block; flex:1 1 auto; max-width:none; \}/.test(css) && /body\.searchOpen \.brand, body\.searchOpen \.rightButtons\{ display:none; \}/.test(css), 'phones: tapping the icon opens a full-width field over the header');
ok(/id="searchToggle"/.test(read('index.html')) && /id="searchCancel"/.test(read('index.html')) && /setOpen\(false\)/.test(app) && /clearSearch\(\)/.test(app.slice(app.indexOf('function setOpen(on)'), app.indexOf('function setOpen(on)') + 400)), 'search opens and collapses (collapse clears the search)');
ok(/\.topbar\{ min-height:48px; padding:3px 8px; gap:6px; flex-wrap:nowrap; \}/.test(css), 'phones: the header is one compact row');
ok(/\.gearBtn\{ width:40px; height:40px; \}/.test(css) && /@media \(pointer:coarse\)\{ \.shareBanner \.pillBtn/.test(css), 'phones: tap targets stay about 40-44px while the padding shrinks');
ok(/#kbdBtn, #helpBtn\{ display:none; \}/.test(css), 'phones: controls that mean nothing on a phone are left out');
ok(/\.searchWrap\{ flex:1 1 320px; max-width:560px;/.test(css) && /font-size:0\.95rem/.test(css.slice(css.indexOf('.searchWrap input{ padding:10px 16px'), css.indexOf('.searchWrap input{ padding:10px 16px') + 140)), 'desktop: the Search bar is larger');
ok(/\.shareBanner #shareBannerText\{ flex:1 1 auto; min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; \}/.test(css) && /\.shareBanner\{ padding:4px 12px; gap:8px; flex-wrap:nowrap;/.test(css), 'the view-only strip is one line with an ellipsis');
ok(/body\.viewStrip #cleanBtn, body\.viewStrip #shareBtn/.test(css) && /classList\.toggle\("viewStrip"/.test(app), 'controls that do nothing on a shared board are hidden');
ok(/rep\.className = "pillBtn"; rep\.textContent = "Report"/.test(app), 'Report stays available on a shared board');
ok(/\.shareBanner #copyToMineBtn\{ display:none; \}/.test(css) === true, 'the big copy button is not shown in the phone strip');
ok(/\}\)\(\);\n/.test(app.slice(app.indexOf('(function syncTopbarHeight'), app.indexOf('(function syncTopbarHeight') + 1200)) && /--chrome-top/.test(app), 'the board always starts directly under the header and strip, whatever their height');
ok(/\.donePile\{ position:fixed; left:14px; bottom:calc\(var\(--done-bottom, 30px\)/.test(css) && /--done-bottom:46px/.test(css) && /--done-bottom:44px/.test(css), 'the Done pile sits lower than before (46 -> 30px on wide screens, 60 -> 44px on phones)');
ok(/env\(safe-area-inset-bottom/.test(css.slice(css.indexOf('.donePile{ position:fixed'), css.indexOf('.donePile{ position:fixed') + 160)), 'the Done pile respects the bottom safe area');
{ // the Done pile (left, 14px, ~110px wide, bottom 30..~64px) must not overlap the minimap strip (centered, bottom 14..44px) where the minimap reaches it
  const donePileRight = 14 + 112, minimapLeft = (w) => (w - Math.min(680, w - 32)) / 2;
  const bottomFor = (w) => (w <= 600 ? 44 : w <= 919 ? 46 : 30);
  const overlaps = (w) => w > 600 && minimapLeft(w) < donePileRight && bottomFor(w) < 14 + 30;
  ok([375, 390, 430, 600, 700, 800, 919, 1024, 1280, 1440].every((w) => !overlaps(w)), 'the Done pile does not overlap the minimap at common widths');
}

// ================================================================ BUTTONS: contrast by tokens
const hex = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const lum = (c) => { const [r, g, b] = c.map((v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); }); return 0.2126 * r + 0.7152 * g + 0.0722 * b; };
const ratio = (a, b) => { const x = lum(hex(a)), y = lum(hex(b)); return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05); };
const tok = (name, scope) => new RegExp(scope + '[^}]*' + name.replace(/-/g, '\\-') + ':(#[0-9a-fA-F]{6})').exec(css.slice(css.indexOf('v0.8.2.1: button states')))[1];
const lightFill = '#9a5d12', lightHover = tok('--btn-fill-hover', ':root'), lightActive = tok('--btn-fill-active', ':root');
const darkFill = '#ffb454', darkHover = tok('--btn-fill-hover', 'body\\.dark'), darkActive = tok('--btn-fill-active', 'body\\.dark'), darkFg = '#1e1a30';
ok([lightFill, lightHover, lightActive].every((c) => ratio(c, '#ffffff') >= 4.5), 'light: white on a primary button is >= 4.5:1 in default, hover and active (' + [lightFill, lightHover, lightActive].map((c) => ratio(c, '#ffffff').toFixed(1)).join(' / ') + ')');
ok([darkFill, darkHover, darkActive].every((c) => ratio(c, darkFg) >= 4.5), 'dark: dark text on the amber is >= 4.5:1 in default, hover and active (' + [darkFill, darkHover, darkActive].map((c) => ratio(c, darkFg).toFixed(1)).join(' / ') + ')');
ok(ratio(tok('--danger-fill-hover', ':root'), '#ffffff') >= 4.5 && ratio(tok('--danger-fill-hover', 'body\\.dark'), darkFg) >= 4.5, 'danger buttons keep readable hover text in light and dark');
ok(/:where\(\.pillBtn:not\(\.primary\):not\(\.dangerFill\), \.gearBtn, \.asAction, \.bmGo, \.tourBtns button:not\(\.primary\)\):not\(:disabled\):hover\{ background-color:color-mix/.test(css), 'the generic hover tint no longer applies to filled buttons (the Save-on-hover bug)');
ok(/\.pillBtn\.primary:not\(:disabled\):hover[^{]*\{ background:var\(--btn-fill-hover\); border-color:var\(--btn-fill-hover\); color:var\(--btn-fg\); filter:none; \}/.test(css), 'a primary button keeps its text colour and gets an explicit hover fill');
ok(/\.pillBtn\.primary:focus-visible[^{]*\{ outline:2px solid var\(--focus\);[^}]*color:var\(--btn-fg\)/.test(css) && /\.pillBtn\.primary:disabled\{ background:var\(--btn-fill\); color:var\(--btn-fg\); \}/.test(css), 'focus-visible and disabled states keep readable text');
ok(/\nbody\{ --btn-fill:var\(--accent-strong\); --btn-fg:var\(--on-accent\); \}/.test(css) && !/:root\{[^}]*--btn-fg/.test(css), 'the button fill / text tokens resolve on body so dark mode gets dark text on amber (found by checking hover states in the browser)');
// the old rule that caused it is the one the new tokens now override, for every primary-style button
ok(['.pillBtn.primary', '.btn.primary', '.tourBtns button.primary', '.addBoardRow button'].every((s) => css.includes(s + ':') || css.includes(s + ',') || css.includes(s + '{')), 'primary-style buttons share the central tokens');

// ================================================================ PILE browsing
const bw = ['pileStep', 'paintPileShown', 'browseIdx', 'openPileBrowser'].map(fn).join('\n');
ok(bw.length > 500 && !/notes\.splice|notes\.push|notes\s*=[^=]|saveNotes\(|\.members\s*=|delete\s+\w+\.pileId|\.pileId\s*=|zCounter/.test(bw.replace(/take\.addEventListener[^\n]*\n?/, '')), 'browsing a pile never changes the board data, the member list, any member or the saved state');
ok(!/pileBrowse/.test(app.match(/var SERIAL_FIELDS = \[[^\]]*\]/)[0]) && !/pileBrowse/.test(fn('persistForm') + fn('serializeNote')), 'the browse position is a view state: never stored or synced');
ok(/pilePrev/.test(app) && /pileNext/.test(app) && /\(browseIdx\(n, live\) \+ 1\) \+ " \/ " \+ live\.length/.test(app), 'a pile shows previous / next and a "3 / 24" index');
ok(/@media \(hover:none\)\{ \.pileObj \.pileNav\{ display:none; \} \}/.test(css) && /pileDownAt\.touch/.test(app) && /openPileBrowser\(n\)/.test(app), 'touch: no hover dependence; a tap opens the browser');
ok(/e\.key === "ArrowRight"/.test(fn('openPileBrowser')) && /dx < 0 \? 1 : -1/.test(fn('openPileBrowser')) && /Back to the pile/.test(fn('openPileBrowser')) && /pile-browser/.test(app), 'the browser has arrows, swipe, keyboard, an index and a way back (Esc via the layer system)');
ok(/\.pbCard\{ width:min\(420px, 100%\)/.test(css), 'the phone browser shows one paper at a time in a card, never a fan of giant papers');
// the data-safety invariant for browsing is enforced again by the sync tests in client.test.mjs (collapsed members are always in the snapshot)

// ================================================================ VIDEO links
{
  const ctx = vm.createContext({ URL, Math, Number, String, isFinite, Object });
  vm.runInContext('var window = globalThis; Stick = {};', ctx); loadScript(ctx, 'js/embed.js');
  const E = ctx.Stick.embed, id = 'dQw4w9WgXcQ';
  const ok1 = (u) => E.parse(u);
  ok(ok1('https://www.youtube.com/watch?v=' + id) && ok1('https://youtu.be/' + id) && ok1('https://m.youtube.com/watch?v=' + id) && ok1('https://youtube.com/shorts/' + id) && ok1('https://www.youtube.com/embed/' + id) && ok1('https://vimeo.com/76979871') && ok1('https://player.vimeo.com/video/76979871'), 'supported YouTube and Vimeo links are detected');
  ok(E.parse('https://youtu.be/' + id + '?t=42').start === 42 && E.parse('https://youtu.be/' + id + '?t=1m30s').start === 90, 'a start time is understood');
  const p = E.parse('https://www.youtube.com/watch?v=' + id + '&list=PLx&utm_source=x');
  ok(p.embedUrl === 'https://www.youtube-nocookie.com/embed/' + id + '?rel=0&modestbranding=1&playsinline=1' && p.watchUrl === 'https://www.youtube.com/watch?v=' + id, 'the embed address is built from the id, on the privacy-enhanced domain, with nothing carried over from the pasted text');
  ok(E.parse('https://vimeo.com/76979871').embedUrl === 'https://player.vimeo.com/video/76979871?dnt=1', 'Vimeo embeds are do-not-track');
  ok(E.parse('https://www.youtube.com/watch?v=' + id).source === 'https://www.youtube.com/watch?v=' + id, 'the original address is preserved');
  const bad = ['http://www.youtube.com/watch?v=' + id, 'https://evil.example/watch?v=' + id, 'https://youtube.com.evil.example/watch?v=' + id, 'https://www.youtube.com/watch?v=short', 'https://www.youtube.com/watch?v=' + id + '"><script>', 'javascript:alert(1)', 'data:text/html,hi', 'https://user:pw@www.youtube.com/watch?v=' + id, 'https://www.youtube.com:8443/watch?v=' + id, 'https://www.youtube.com/playlist?list=abc', 'https://vimeo.com/channels/staffpicks', 'https://example.com/clip.mp4', '', null, 'not a url', 'https://www.youtube.com/watch?v=' + id + ' extra'];
  ok(bad.every((u) => E.parse(u) === null), 'unsupported, unsafe or malformed addresses are rejected and stay ordinary links');
  ok(E.normalize({ type: 'embed', url: 'https://youtu.be/' + id, w: 99999 }).w === 640 && E.normalize({ type: 'embed', url: 'https://evil.example/x' }) === null, 'a stored embed is re-derived and clamped; a bad one is unreadable (kept, never deleted)');
  ok(!/\bf\.src = (n|info)\.(url|source)\b/.test(app) && /f\.src = info\.embedUrl \+ "&autoplay=1"/.test(app), 'the iframe source is only ever the built embed address, never the pasted one');
  ok(/sandbox/.test(fn('embedPlay')) && /referrerpolicy/.test(fn('embedPlay')) && /loading/.test(fn('embedPlay')), 'the player is sandboxed, lazy and privacy-referrer');
  ok(/askVideoChoice\(vInfo\)/.test(fn('pasteAsNewNote')) && /Keep as link/.test(fn('askVideoChoice')) && /Show as embedded video/.test(fn('askVideoChoice')) && /v === "embed" \? "embed" : "link"/.test(fn('askVideoChoice')), 'a pasted video link asks Keep as link or Show as embedded video; dismissing keeps it as a link');
  ok(/addNoteAt\(vc0\.x, vc0\.y - 60/.test(fn('pasteAsNewNote')), 'keeping it as a link creates the normal link note');
  ok(/function embedToLink/.test(app) && /linkNoteHtml\(n\.url\)/.test(fn('embedToLink')) && /function linkToEmbed/.test(app) && /swapObject/.test(fn('embedToLink')), 'an embed can be turned back into a normal link (and a link note into an embed), as one undo step');
  ok(/IntersectionObserver/.test(fn('embedWatch')) && /embedStop\(m\)/.test(fn('embedWatch')) && /embedObserver\.unobserve\(elRef\)/.test(fn('removeNoteEl')), 'an offscreen player is unmounted and a deleted one is released');
  ok(/frame-src https:\/\/www\.youtube-nocookie\.com https:\/\/player\.vimeo\.com;/.test(read('index.html')) && !/frame-src[^;]*\*/.test(read('index.html')), 'the CSP allows frames only from the two provider hosts');
  ok(/c\.type === "embed"/.test(fn('cloudSanitize')) && /Stick\.embed\.normalize\(c\)/.test(fn('cloudSanitize')) && /item\.type === "embed"/.test(fn('normalizeIncoming')), 'embeds survive sync and import through the same validation');
  ok(/"url","provider","vid","start"\]/.test(app.match(/var SERIAL_FIELDS = \[[^\]]*\]/)[0]) && /embed\.js/.test(read('index.html')), 'embed fields are stored and the module is loaded');
  ok(/n\.type === "embed"/.test(fn('noteHasContent')), 'an embed is never treated as an empty note');
}

// ================================================================ versions and docs
const pn = JSON.parse(read('docs/patch-notes/patch-notes.json'));
ok(pn[0].version === '0.8.2.1' && pn[0].codename === 'Room to Breathe' && pn[0].status === 'development' && pn[0].date === null, 'v0.8.2.1 "Room to Breathe" is recorded and not released');
ok(/APP_VERSION: "0\.8\.2\.1", APP_CODENAME: "Room to Breathe", APP_STATUS: "development"/.test(read('js/config.js')), 'the app version is 0.8.2.1, status development');
ok(fs.existsSync(path.join(root, 'docs/patch-notes/0.8.2.1.md')) && JSON.parse(read('docs/patch-notes/index.json'))[0].file === '0.8.2.1.md', 'patch notes and the index are in step');
ok(pn[0].tour.length >= 6 && pn[0].tour.some((s) => /Legal/.test(s.title)) && pn[0].tourMode === 'full', 'the Spotlight tour is data in the existing patch system and points at Legal');
ok(fs.existsSync(path.join(root, 'docs/dev/PRE-BETA-CHECKLIST.md')) && /not\*\* replace|does \*\*not\*\* replace/.test(read('docs/dev/PRE-BETA-CHECKLIST.md')), 'the pre-beta checkpoint is recorded');

console.log('v0.8.2.1: ' + pass + ' passed, ' + fail + ' failed');
process.exit(fail ? 1 : 0);
