// Generated by tools/build-patch-data.mjs from docs/patch-notes/patch-notes.json. Do not edit by hand.
(function (root) { var Stick = root.Stick = root.Stick || {}; Stick.patchData = {
  "version": "0.8.3.3",
  "codename": "Sand the Edges",
  "tldr": "A focused hotfix for tutorial bugs, piles, zones, reactions, legal pages, editing, system-space UI and the little interactions that still felt unfinished.",
  "highlights": [
    "Things stopped overlapping: pile controls, modals and Zone chrome got a cleanup pass.",
    "Tutorials behave again: keyboard navigation and patch-history replay were repaired.",
    "Paper feels smarter: empty notes skip Trash, trimming is automatic with Undo, and Newspaper editing behaves consistently.",
    "Same Stick-It, fewer weird bits: reactions, Settings, Legal pages, Video creation and profile controls got polished."
  ],
  "tourMode": "full",
  "tour": [
    {
      "target": null,
      "title": "Sand the Edges",
      "body": "A small hotfix for the things that worked but still felt wrong. This takes about thirty seconds."
    },
    {
      "target": null,
      "title": "Things stopped overlapping",
      "body": "Pile controls, modals and Zone chrome got a cleanup pass. Confirmations now always appear above Done and Trash.",
      "feature": "layers"
    },
    {
      "target": null,
      "title": "Tutorials behave again",
      "body": "Enter and the arrow keys move through a tour, Skip always works, and every old patch tour can be replayed from What’s New.",
      "feature": "patchNotes",
      "action": "openPatchNotes"
    },
    {
      "target": null,
      "title": "Paper feels smarter",
      "body": "Closing a brand-new empty note skips Trash, spare paper trims itself (with Undo), and Newspaper copy and paste behaves consistently.",
      "feature": "paper"
    },
    {
      "target": null,
      "title": "Same Stick-It, fewer weird bits",
      "body": "Reactions, Settings rows, the Legal pages, Add video and the profile photo control all got polished.",
      "feature": "polish",
      "action": "openShortcuts"
    }
  ]
}; })(typeof window !== "undefined" ? window : globalThis);
