// Generated by tools/build-patch-data.mjs from docs/patch-notes/patch-notes.json. Do not edit by hand.
(function (root) { var Stick = root.Stick = root.Stick || {}; Stick.patchData = {
  "version": "0.8.2.2",
  "codename": "Touch the Paper",
  "tldr": "More physical controls, less menu clutter, and objects that behave a little more like the things they represent.",
  "highlights": [
    "Pin it for real: a physical tack drops onto the paper (and falls away when you unpin).",
    "Turn things a little sideways: rotate notes and scraps by hand, snap with Shift, or straighten.",
    "Links can become videos: turn an existing video link into something playable without pasting it again.",
    "Cleaner menus: Paper controls live under Paper, turning controls under Arrange, and Delete looks like Delete."
  ],
  "tourMode": "full",
  "tour": [
    {
      "target": null,
      "title": "Touch the Paper",
      "body": "More physical controls, less menu clutter. This takes about thirty seconds."
    },
    {
      "target": ".note",
      "title": "Pin it for real",
      "body": "Pinning a note now looks like pinning a note. Tack included. Press P on a selected note and watch it drop."
    },
    {
      "target": ".note",
      "title": "Turn things a little sideways",
      "body": "Select a note and drag the small turn handle at its corner. Hold Shift to snap, double-click it to straighten, or use Arrange in the ... menu."
    },
    {
      "target": null,
      "title": "Links can become videos",
      "body": "Already pasted a video link? Click it and choose Play in Stick-It to turn it into something playable on the board."
    },
    {
      "target": ".moreBtn",
      "title": "Cleaner menus",
      "body": "Paper controls now live with Paper controls, and turning lives under Arrange. Delete turns red when you point at it."
    }
  ]
}; })(typeof window !== "undefined" ? window : globalThis);
