// Writes js/build-info.js: a build number (the commit count including the commit being made) and the time, shown in the corner of the app so the live site can always be told apart.
// Run automatically by .git/hooks/pre-commit (see docs/dev/BUILD-STAMP.md); safe to run by hand.
import { execSync } from 'node:child_process'; import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
let n = 0; try { n = Number(execSync('git rev-list --count HEAD', { cwd: root }).toString().trim()) + 1; } catch (e) { n = 0; }
const d = new Date(), p = (x) => String(x).padStart(2, '0'), at = d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate()) + ' ' + p(d.getHours()) + ':' + p(d.getMinutes());
fs.writeFileSync(path.join(root, 'js', 'build-info.js'), '/* GENERATED by tools/stamp-build.mjs on every commit. Do not edit. */\n(function (r) { var S = r.Stick = r.Stick || {}; S.build = { n: ' + n + ', at: "' + at + '" }; })(typeof window !== "undefined" ? window : globalThis);\n');
console.log('build ' + n + ' ' + at);
